<a href="https://colab.research.google.com/github/ysn-gachon/AI-Class-202335225-nayeonsu/blob/main/Week%2015/spam_male_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [3]:

docs = [ 'additional income',
         'best price',
         'big bucks',
         'cash bonus',
         'earn extra cash',
         'spring savings certificate',
         'valero gas marketing',
         'all domestic employees',
         'nominations for oct',
         'confirmation from spinner']

labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=', accuracy)

test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

[[24, 12], [47, 12], [12, 35], [11, 20], [9, 41, 11], [40, 33, 48], [11, 3, 46], [32, 40, 4], [26, 12, 18], [16, 31, 6]]
[[24 12  0  0]
 [47 12  0  0]
 [12 35  0  0]
 [11 20  0  0]
 [ 9 41 11  0]
 [40 33 48  0]
 [11  3 46  0]
 [32 40  4  0]
 [26 12 18  0]
 [16 31  6  0]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


정확도= 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[[0.5443247]]
